export const projects = [
  {
    title: "E-Commerce Platform",
    description: "A frontend e-commerce platform with cart, payments, and products.",
    tech: ["React.js", "Express.js", "Node.js", "MongoDB"],
    github: "https://github.com/zees123-svg/CodeAlpha_Simple-E-commerce-Store",
    demo: "#",
    image: "/projects/Ecommerce.jfif",
    icon: "🛒",
  },
  {
    title: "Task Management App",
    description: "Collaborative task management tool with real-time updates and team features.",
    tech: ["React.js", "Express.js", "Node.js", "MongoDB"],
    github: "https://github.com/zees123-svg/Syntecxhub_Task-Manager-Mern-App",
    demo: "#",
    image: "/projects/Taskmanager.jfif",
    icon: "✅",
  },
  {
    title: "Portfolio Website",
    description: "Modern portfolio website built with Next.js and Tailwind CSS.",
    tech: ["Html", "CSS", "Javascript", "Framer Motion"],
    github: "https://github.com/zees123-svg/Portfolio4",
    demo: "https://portfolio4-liart-kappa.vercel.app/",
    image: "/projects/Portfolio 2.png",
    icon: "🎨",
  },
  {
    title: "Weather Website",
    description: "Real-time weather tracking with interactive google weather forecasts feature.",
    tech: ["React", "Weather API", "Javascript", "CSS"],
    github: "https://github.com/zees123-svg/Syntecxhub_Weather_App",
    demo: "#",
    image: "/projects/Weather.jfif",
    icon: "🌤️",
  },
  {
    title: "Social Media App",
    description: "Full-featured social platform with posts, likes, and comments.",
    tech: ["React.js", "Node.js", "Express.js", "MongoDB"],
    github: "https://github.com/zees123-svg/CodeAlpha_Social-Media-Platform",
    demo: "#",
    image: "/projects/Socialmedia.jfif",
    icon: "📱",
  },
  {
    title: "Mern Blog App",
    description: "Full-featured blog platform with content management, user authentication, and comment system.",
    tech: ["React.js", "Node.js", "Express.js", "MongoDB"],
    github: "https://github.com/zees123-svg/Syntecxhub_Mern-Blog-Application",
    demo: "#",
    image: "/projects/Blog.jfif",
    icon: "📱",
  },
];

export const skills = [
  { name: "Html", icon: "html", level: 85 },
  { name: "Css", icon: "css", level: 80 },
  { name: "Tailwind CSS", icon: "tailwind", level: 75 },
  { name: "JavaScript", icon: "javascript", level: 70 },
  { name: "React.js", icon: "react", level: 65 },
  { name: "Next.js", icon: "nextjs", level: 60 },
  { name: "Node.js", icon: "nodejs", level: 65 },
  { name: "Mysql", icon: "mysql", level: 75 },
  { name: "Git", icon: "git", level: 75 },
  { name: "Github", icon: "github", level: 80 },
];